- name: demo using rzfeeser.mtg.card lookup plugin
  hosts: localhost
  gather_facts: false
  connection: ansible.builtin.local

  vars:
    card_info: "{{ lookup('rzfeeser.mtg.card', 'Archangel%20Avacyn') }}"

  tasks:

  - name: display card_info obtained by using the lookup plugin
    ansible.builtin.debug:
      var: card_info
